pipeline:
  name: OSINT-Web-CI-Frontend
  identifier: OSINTWebCIFrontend
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: osint-vm-clone
        build: <+input>
  stages:
    - stage:
        name: build-froentend-package
        identifier: buildfroentendpackage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: |-
                      set -euo pipefail
                      echo "Building frontend (dev mode)..."
                      cd frontend && npm ci && npm run build:dev

                      echo "Copying build to backend/public..."
                      rm -rf backend/public
                      mkdir -p backend/public
                      cp -r frontend/dist/* backend/public/
                      echo "Installing backend production deps..."
                      (cd backend && npm ci --production)
                      echo "Dev build complete."
                  description: building frontend
