pipeline:
  name: OSINT-Web-CI-Frontend
  identifier: OSINTWebCIFrontend
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: osint-vm-clone
        build: <+input>
  stages:
    - stage:
        name: build-froentend-package
        identifier: buildfroentendpackage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: |-
                      #!/usr/bin/env bash
                      set -euo pipefail
                      echo "Building backend (dev)..."
                      cd backend
                      npm ci
                      npx babel src --out-dir dist/dev --copy-files --extensions ".js"
                      echo "Building frontend (dev)..."
                      cd ../frontend
                      npm ci
                      npm run build:dev
                      echo "Copying frontend build into backend dist/dev/public..."
                      rm -rf ../backend/dist/dev/public || true
                      mkdir -p ../backend/dist/dev/public
                      cp -r dist/* ../backend/dist/dev/public/
                      echo "Dev build complete."
                  description: building frontend
